### PR TITLE
New CIF starting with "J" fix + Test suite

### PR DESCRIPTION
**Pull request by dgilperez**
There you go! 

https://github.com/javiertoledo/spanish_vat_validators/pull/7 and https://github.com/javiertoledo/spanish_vat_validators/pull/8 are also included in this PR.

### CODE REVIEW

**Comment by dgilperez** [comment]
🍻

**Comment by dgilperez** [comment]
Are you ok with releasing a new version?

**Comment by deivid-rodriguez** [comment]
Nice! Thanks to both! :tada: :tada:

**Comment by deivid-rodriguez** [comment]
Yeah, a new release would be nice! :)

**Comment by javiertoledo** [comment]
New version released, thanks everyone! https://rubygems.org/gems/spanish_vat_validators/versions/0.0.6

**Pull request merged**
